# Generated by Django 4.2.5 on 2023-09-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='wishlist_status',
            field=models.BooleanField(default=False),
        ),
    ]
